"""TreeBuilder — builds and updates the memory tree from RAW + Refined."""

import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from sisyphus.memory.store import Memory, MemoryStore
from sisyphus.memory.refined import RefinedStore
from sisyphus.memory.tree import TreeStore, TreeNode


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id(prefix: str = "n") -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


class TreeBuilder:
    """Builds a memory tree by clustering memories by type/tag and title similarity.

    Clustering is purely heuristic (no LLM). When no LLM is available,
    summaries are generated by concatenating titles within each cluster.
    """

    def __init__(self, tree: TreeStore, store: MemoryStore, refined: RefinedStore):
        self.tree = tree
        self.store = store
        self.refined = refined

    def build(self) -> List[str]:
        """Run the full build pipeline. Returns list of created L1 node IDs."""
        raw_mems = self.store.list()
        refined_mems = self.refined.list_refined()
        all_mems = raw_mems + refined_mems

        clusters = self._coarse_cluster(all_mems)
        l1_ids = []
        for cluster_title, mems in clusters:
            subclusters = self._fine_cluster(mems, threshold=0.3)
            for sub_mems in subclusters:
                titles = [m.title for m in sub_mems]
                summary = self._summary_from_titles(titles)
                l1_node = self._upsert_l1(cluster_title, summary)
                l1_ids.append(l1_node.id)
                for m in sub_mems:
                    if not self._leaf_exists(m.id):
                        self.tree.add_leaf(l1_node.id, m.title, m.content[:200])

        self._update_l0()
        return l1_ids

    def _coarse_cluster(self, memories: List[Memory]):
        """Group by type. Returns list of (cluster_title, [Memory])."""
        groups = {}
        for m in memories:
            key = m.type
            groups.setdefault(key, []).append(m)
        result = []
        for mem_type in sorted(groups):
            result.append((f"Type: {mem_type}", groups[mem_type]))
        return result

    def _fine_cluster(self, memories: List[Memory], threshold: float = 0.3):
        """Within a type group, split into sub-clusters by title similarity."""
        if not memories:
            return []
        assigned = [False] * len(memories)
        clusters = []
        for i in range(len(memories)):
            if assigned[i]:
                continue
            cluster = [memories[i]]
            assigned[i] = True
            for j in range(i + 1, len(memories)):
                if assigned[j]:
                    continue
                sim = self._title_similarity(memories[i].title, memories[j].title)
                if sim >= threshold:
                    cluster.append(memories[j])
                    assigned[j] = True
            clusters.append(cluster)
        return clusters

    @staticmethod
    def _title_similarity(a: str, b: str) -> float:
        """Jaccard similarity on word tokens."""
        if not a or not b:
            return 0.0
        words_a = set(a.lower().split())
        words_b = set(b.lower().split())
        if not words_a or not words_b:
            return 0.0
        intersection = words_a & words_b
        union = words_a | words_b
        return len(intersection) / len(union)

    @staticmethod
    def _summary_from_titles(titles: List[str]) -> str:
        """Build summary by concatenating titles (LLM-free fallback)."""
        return "; ".join(titles) if titles else ""

    def _upsert_l1(self, cluster_title: str, summary: str) -> TreeNode:
        """Find existing L1 node for this cluster, or create one."""
        existing = self._find_l1_by_title(cluster_title)
        if existing is not None:
            existing.summary = summary
            existing.updated_at = _now()
            self.tree._write_node(existing)
            return existing
        node = TreeNode(
            id=_new_id("l1"),
            parent_id="l0",
            level=1,
            title=cluster_title,
            summary=summary,
        )
        self.tree._write_node(node)
        self.tree._update_meta_add(node)
        return node

    def _find_l1_by_title(self, title: str) -> Optional[TreeNode]:
        """Look up an existing L1 node by title."""
        for node in self.tree.list_nodes(level=1):
            if node.title == title:
                return node
        return None

    def _leaf_exists(self, memory_id: str) -> bool:
        """Check if a leaf node for this memory already exists."""
        all_nodes = self.tree.list_nodes(level=2)
        return any(n.title == memory_id or n.id.endswith(memory_id[-12:]) for n in all_nodes)

    def _update_l0(self):
        """Update l0 global summary from all L1 cluster titles."""
        l0 = self.tree.get_node("l0")
        if l0 is None:
            return
        l1_nodes = self.tree.list_nodes(level=1)
        titles = [n.title for n in l1_nodes]
        l0.summary = self._summary_from_titles(titles)
        self.tree._write_node(l0)
